### ISSUE TITLE
Check and correct installation procedure

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#13]
Someone should check the code dependencies and simplify installation.

Perhaps our aims should be the following:
1. ensure easy pip installation on a system which already has hammurabiX installed
2. find out how (or whether it is possible) to upload hammurabiX to [conda-forge](https://anaconda.org/conda-forge) and make the whole project conda-installable
3. update the dockerfile (potentially, using 2) and upload a docker image to dockerhub, using a IMAGINE collaboration account
4. Set up "GitHub actions" to update the [Docker image](https://github.com/IMAGINE-Consortium/imagine/new/master?filename=.github%2Fworkflows%2Fdocker-image.yml&workflow_template=docker-image) and [PyPI package](https://github.com/IMAGINE-Consortium/imagine/new/master?filename=.github%2Fworkflows%2Fpython-publish.yml&workflow_template=python-publish)

Tentative task-list:
- [x] Check and update requirements.txt
- [x] Check and update imagine_conda_env.yml
- [x] Adjust the installation docs
-  ~Set up a PyPI IMAGINE package~ (For later?)
- [x] Update the dockerfile
- [x] Upload docker image to ~DockerHub~ GitHub packages
- [x] ~Set up GitHub Actions (?)~ set up Travis CI
- ~Make the bundle IMAGINE+HammurabiX conda-installable (uploading to conda-forge)~

**Comment by luizfelippesr** [comment]
Task-list:
- [ ] Check and update requirements.txt
- [ ] Check and update imagine_conda_env.yml
- [ ] Set up a PyPI IMAGINE package
- [ ] Update the dockerfile
- [ ] Upload dockerfile to DockerHub
- [ ] Set up GitHub Actions
- [ ] Make the bundle IMAGINE+HammurabiX conda-installable (uploading to conda-forge)

**Comment by 1313e** [comment]
So, the big problem here, is `PyMultiNest`.
That package does not handle the installation of `MultiNest` (which it should actually), thus kind of forcing us to do it properly.
`hampyx` has a similar problem, but as that is an affiliated package, we can fix that.
Without `PyMultiNest` being able to be installed properly using `pip install`, `imagine` itself cannot be converted to a PyPI-compatible package.

**Comment by 1313e** [comment]
Also, one other thing: You can actually add GitHub repos to the `requirements.txt` file, and `pip` will clone and install them.
Keep in mind however that any packages that are uploaded to PyPI CANNOT rely on any packages that need to be cloned.
This is a security rule that PyPI has and cannot be circumvented.

**Comment by luizfelippesr** [comment]
> That package does not handle the installation of `MultiNest` (which it should actually), thus kind of forcing us to do it properly.

Interestingly,  `conda install pymultinest` does the job... is one of those examples where the conda route  is easier

**Comment by luizfelippesr** [comment]
> Also, one other thing: You can actually add GitHub repos to the `requirements.txt` file, and `pip` will clone and install them.
> Keep in mind however that any packages that are uploaded to PyPI CANNOT rely on any repos that need to be cloned.
> This is a security rule that PyPI has and cannot be circumvented.

This is unfortunate, but makes sense.

**Comment by luizfelippesr** [comment]
While some adjustments are still needed, the main points of this issue were addressed. For the sake of organisation, I will close it and spawn specialised issues regarding CI/CD where necessary.

The conda-forge idea can be left for a distant future (as it is non-essential).
