### ISSUE TITLE
Random seeds need checking

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#15]
When I execute the convergence test in the end of tutorial_one, I get always the same answer, despite the fact that `pipeline.random_type = 'free'` was used.

(This refers to the new_field branch)

**Comment by gioacchinowang** [comment]
with only dynesty pipeline or both pipelines?

**Comment by luizfelippesr** [comment]
It is actually the new ultranest pipeline. I probably broke or misunderstood something while refactoring the base pipeline class.

**Comment by luizfelippesr** [comment]
Indeed, there was a mistake in the implementation of the new pipeline base: the attribute `samples` which I was using to do the plotting in tutorial_one was not been reset between executions. This has been fixed.

Nevertheless, I reorganised a bit the way the `random_type`s work. Hopefully, with the explanation added to the end of tutorial_one, it is more clear now what the difference between 'controllable', `'free'  and 'fixed' modes.
