### ISSUE TITLE
Restore logging  capabilities

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#16]
Base classes should have logging capability.  A lot of this was already there before the refactoring.

At the very least, the logs should allow one know which parameters were used by each component at each stage.  Later, we could consider logging function calls. A standard "logging interface" for new samplers would also be a good idea.

**Comment by 1313e** [comment]
I guess I will assign myself to a few of these issues, so I know for later that I should spend my time on them.

**Comment by luizfelippesr** [comment]
A simple and useful provisional plan for logging:

- [x]  Keep the present debug infra-structure which reports function/method calls using `logging.DEBUG`
- [ ]   Use the `logging.INFO` level to log the (scaled) values of the parameters and the resulting likelihood every time the core_likelihood is called
- [ ] Document this (perhaps exemplifying the setup in tutorial_five).
