### ISSUE TITLE
Pipeline test-run

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#21]
Before running an IMAGINE pipeline there are many basic questions which need (at least approximate) answering:
* Which grid resolution is adequate?
* What is the optimal ensemble size?
* Roughly how long will a pipeline run take?

It is possible to get an idea of the answers to these questions looking at the final likelihood function being computed, which can be accessed in IMAGINE 2.0.0 through the method `pipeline._likelihood_function()`.   If the grid resolution and/or the ensemble size are too small, the likelihood becomes extremely noisy. If they are too high, the computational cost of each evaluation becomes huge.  

A good testing tool (this could be a new `pipeline` method) would choose a few neighbouring points in the parameter space and evaluate the likelihood function on them. This would be repeated for different ensemble sizes and grid sizes, and the variability and the run-times associated with each of them would be reported.

**Comment by luizfelippesr** [comment]
As an example, the following plots show the likelihood of tutorial_one, evaluated on a uniform 25x25 grid of parameter choices, in the range 2<a<5 and 3.5<b<6.5. The spatial grid where the fields were evaluated had a resolution 125x1x1.  
This setup allows visualizing how the noise due to small sample sizes, prevents one from finding the maximum likelihood region.

![image](https://user-images.githubusercontent.com/11710467/85272465-7fb90e00-b47c-11ea-9a61-a7e1df5b58aa.png)
![image](https://user-images.githubusercontent.com/11710467/85272603-ab3bf880-b47c-11ea-8139-0fedf9dc4a6d.png)
![image](https://user-images.githubusercontent.com/11710467/85272942-2a313100-b47d-11ea-9ee3-b55326243ed9.png)
![image](https://user-images.githubusercontent.com/11710467/85273142-81370600-b47d-11ea-8a98-3cb5ca70eaf9.png)

So, the main questions are: what is the best way to quantify the "likelihood noise" due to limited ensemble sizes? How does the uncertainty in the likelihood propagate to the uncertainty in the evidence? How does the posterior degrade due to the likelihood uncertainty?

**Comment by trjaffe** [comment]
I'm not sure that this is a fair comparison.  With fewer samples *at each grid point*, and the same number of grid points, of course more samples is better.  But that's not how the sampling works.  The comparison should be for the same total number of simulator runs.  So instead of comparing an ensemble jof 750 samples on each of 25x25 grid points (roughly half a million simulations), you should compare the case of an ensemble size of 60 with a grid of 90x90 (roughly half a million simulations).

**Comment by luizfelippesr** [comment]
I am not sure I follow.  If I make coarse grained version of the last plot, the few points on the resulting figure will still describe the shape of the same surface. Thus, even in the coarse grained plot it will be possible to roughly identify the region in the parameter space where likelihood is largest. While in the first plot, the noise prevents me to make any statement, at least "by eye".

It is possible that the noise cancels out, somehow, while computing the marginal likelihood, as it involves an integral... but I find it hard to believe that the sampler would work properly if the gradients are so poorly defined as in the first figure.  Moreover, even if the marginal likelihood/evidence does converge, what about the posterior (and "best fit" values for parameters) estimates?

**Comment by trjaffe** [comment]
Your first para is correct.  But you only computed 40k realizations compared to 500k.  So it makes sense that there is less information in the first plot than in the last plot.  To my understanding, it's just a question of how many simulations you're averaging together into each likelihood bin.  You can have a larger ensemble at each point in likelihood space, or you can have fewer ensembles at each point but evaluate more points (i.e. a higher density in likelihood space).  

Indeed, the question is very much about how the sampler will behave.  With a straightforward MCMC, I found that a larger ensemble at each point did *not* help, in the sense that though it required fewer likelihood samples, it didn't change the total run time to get a decent convergence.  But this is very sampler dependent.  And indeed, our non-deterministic likelihood is very unusual, so there's not a lot of literature about how to handle this.  

One thing that I did (and I found a few other analyses that did this as well) was to smooth the likelihood space at the end.  The sampling would also have worked better if I could have done this *during* the sampling as well.   It would be handy if one of the Python samplers allowed us to re-compute the current posterior distribution, specifically to smooth it, periodically during the run.

**Comment by gioacchinowang** [comment]
I think the nested sampler won't complain that much about the "likelihood noise" as it exclude parameter space patches in each round of killing a fraction of the live points. For the ensemble size I would suggest it be at least 10% of the data size, but this is empirical.
