### ISSUE TITLE
Abstract Base Classes

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#24]
As @1313e pointed out, it would be useful (and good practice) to write IMAGINE base classes as [abstract base classes](https://docs.python.org/3/library/abc.html).

An Absctract Base Class cannot be directly instantiated, and its subclasses must contain implementation for the any methods with the `@abstractmethod` decorator. This prevents many possible mistakes.

Here is a list of the classes which should become ABC
- [x] GeneralField
- [x] ~GeneralFieldFactory~
- [x] Likelihood
- [x] Simulator
- [x] Pipeline
- [x] ObservableDict

**Comment by 1313e** [comment]
Why is `GeneralFieldFactory` a base class?
It has no attributes that require overriding.
One could simply make it a default factory, and initialize it with the definition of a `GeneralField`.

**Comment by luizfelippesr** [comment]
> Why is `GeneralFieldFactory` a base class?
> It has no attributes that require overriding.
> One could simply make it a default factory, and initialize it with the definition of a `GeneralField`.

Good point.  Agreed: it does make sense to adjust `GeneralFieldFactory` initialization so that it can be used without subclassing.

**Comment by 1313e** [comment]
> Good point. Agreed: it does make sense to adjust `GeneralFieldFactory` initialization so that it can be used without subclassing.

I will see if I can do that.
First, I want to get everything converted and working properly.

**Comment by 1313e** [comment]
You can see [here](https://github.com/1313e/imagine/blob/1313e_dev/imagine/fields/test_field.py#L40) btw, that I have changed it already to be nothing more than just a shell.
