### ISSUE TITLE
icy decorator - remove it?

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#25]
The `@icy` decorator prevents new attributes to be added to an object/class.  While this may prevent some specific types of error (e.g. typos in attributes name), it makes the code less modular (as it prevents one from adding extra structures to derived classes).

Is there any strong argument for keeping the `@icy` anywhere in the code?

**Comment by icy** [comment]
Hi everyone, I'm glad to be here. The topic mentioned me who has no idea about your project honestly ;P

Is there something I can help?

Cheers

**Comment by luizfelippesr** [comment]
Sorry @icy, we mentioned you by mistake.

**Comment by icy** [comment]
@luizfelippesr never mind. it's fun. I think it's about github issue. Mention feature shouldn't work when a string is embeded in code/pre-formatted characters.

Anyway I have enough noise ;) Cheers

**Comment by gioacchinowang** [comment]
Nope, we can remove it.

**Comment by 1313e** [comment]
I already did
