### ISSUE TITLE
examples directory needs checking

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#29]
Most of the examples in the examples directory need to be rewritten, as they have not been updated after refactoring/redesign.

**Comment by gioacchinowang** [comment]
The examples are repeating what have been implemented in the tutorials, so I guess we can just remove the `examples`?

**Comment by luizfelippesr** [comment]
Well, the two new examples are not exactly the same thing as the tutorials.

My suggestion is the following: the 'basic_example.py' could be improved, allowing one to choose which Pipeline to use (thus illustrating the use of the 3 of them).  'example_pipeline.py' could be slightly adjusted/improved. 

After that, I think the old tests could perhaps be removed and this issue closed.
