### ISSUE TITLE
Pipeline saving, and resuming after interruption

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#32]
There is still no implemented standard way of saving the state of the IMAGINE `Pipeline` object. This would be very useful.

In particular, this could be done automatically just before the sampler starts running and if an interruption signal is caught. As most samplers allow resuming a run, saving the state of the assembled `Pipeline` (and thus the final likelihood function and prior transform) will allow continuing the run.

As the `Pipeline` also stores results, its state should probably also be saved after the run finishes. This would allow one to submit a script which assembles and runs a `Pipeline` on a cluster and later examine the results by inspecting the loaded `Pipeline`.

**Comment by luizfelippesr** [comment]
It looks like the `dill` package can easily save and load a pipeline object, allowing accessing samples, simulator, field factories, priors, etc.  

Thus, a tool for saving and loading an IMAGINE setup is not only feasible, but relatively simple to implement.

The pipeline loading/saving tool should be able to do the following:

* **saving**
    - use dill to save the pipeline
    - save the rc variables
    - save the chains directory
* **Loading**
    - optionally load and use rc variables
    - load pipeline
    - adjust chains directory attribute to actual saved directory

Perhaps matters could be simplified if the user provides a *run directory* when the Pipeline is created.

**Comment by luizfelippesr** [comment]
cd4be53

**Comment by 1313e** [comment]
I hope you use `hickle` to save the state of the pipeline, as it allows you to store it easily in a single file.
