### ISSUE TITLE
Pipeline interface improvements

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#38]
The `Pipeline` sub-classes need better, hopefully standardized, interfaces, to avoid forcing the user to reach on each sampler docs to choose the sampling_controllers. 

**Specification/checklist**

* ~The main parameters controlling the samplers should became keyword arguments~
* Docstrings should describe each of these 
  - [x] MultinestPipeline
  - [x] DynestyPipeline
  - [x] UltranestPipeline
- [x] Standard temporary (or permanent, if set) directory for the chains
* ~Progress monitoring~ (Still difficult to do this in a general way.)

**Comment by 1313e** [comment]
It might be a bit hard to find a proper way to do this, as every package is different, but e13Tools has 3 decorators, used for appending (`e13tools.docstring_append`); copying (`e13tools.docstring_copy`); and substituting (`e13tools.docstring_substitute`) docstrings.
They are useful for making sure that docstrings are consistent when used in multiple places; reusing docstrings from other definitions; or making changes to docstrings that are only known at import-time (like, you could have a docstring that reflects which OS you are using).

**Comment by luizfelippesr** [comment]
After experimenting (i.e. implementing the keywords for `UltranestPipeline` and playing with tutorial_one) , I changed my mind about this (this is why I have just updated the issue description).

The `sampling_controllers` attribute is actually very convenient, since all the required arguments are in the same place. If the user wants to re-run the pipeline (as in the convergence check in the end of tutorial_one),  the previously used sampling controllers are re-used nicely.  While defining an IMAGINE pipeline on a script, the sampling controllers force you to (usually) have a separate line of code regarding sampler-specific parameters (which is good). 

So my current plan now is to make the `sampling_controllers` more useful, the steps for this, I think, are the following:  1) `sampling_controlllers` for each Pipeline subclass should be documented, 2) there should be IMAGINE-specific default values,  3) After running the pipeline the full list of `sampling_controllers` should be available to the user (allowing they to inspect what exactly they used).

**Comment by luizfelippesr** [comment]
> It might be a bit hard to find a proper way to do this, as every package is different, but e13Tools has 3 decorators, used for appending (e13tools.docstring_append); copying (e13tools.docstring_copy); and substituting (e13tools.docstring_substitute) docstrings.

These look very useful, but I am not sure it will help in our case.  For example, in the UltraNest case,  there are  some arguments which are used to initialize UltraNest, others which are used to run it, but within IMAGINE all of them are `sampling_controllers`. Also, there are sampler arguments which *should not* show up for an IMAGINE user (e.g. `loglike` which sets the likelihood function).

**Comment by luizfelippesr** [comment]
b043acd664a00e6a85f4e6631edf591fb4969d62

**Comment by 1313e** [comment]
> These look very useful, but I am not sure it will help in our case. For example, in the UltraNest case, there are some arguments which are used to initialize UltraNest, others which are used to run it, but within IMAGINE all of them are `sampling_controllers`. Also, there are sampler arguments which _should not_ show up for an IMAGINE user (e.g. `loglike` which receives the likelihood function, should be set internally within IMAGINE).

You are right, which is why I mentioned that it might be hard to find a proper way to do this.
I just wanted to mention them in case you can see somewhat of an overlap between their docstrings and the ones you need.
