### ISSUE TITLE
Standard plotting methods/functions?

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#41]
Corner plots (and, perhaps also, traceplots) are essential tools for working with samplers. 

Tutorial one illustrates how to use two different tools to show corner plots but it would be useful to have these as methods of the pipeline itself, allowing the user a quick diagnostic.  In fact, by default, the Pipeline should perhaps show a corner plot after it runs on a jupyter notebook (forcing the user to at least have a quick look at it).

One attractive possibility is using the [ChainConsumer](https://github.com/Samreay/ChainConsumer) package (suggested by @1313e) for this and other plotting/analysis tasks.

**Comment by 1313e** [comment]
[CMasher](https://github.com/1313e/CMasher) holds a large collections of scientific colormaps, which may be useful as well.

**Comment by luizfelippesr** [comment]
Quick note on this:  there should be some kind of "verbosity" option which makes the code redraw (or save somewhere) standard diagnostic plots every N evaluations of the likelihood function.  This is a natural and generic way of keeping track of what is going on while the pipeline runs.

**Comment by 1313e** [comment]
You would want to turn that plotting off by default, as it is annoying to get large number of figures dumped to disk when you didn't ask for them.
