### ISSUE TITLE
Fix the unit tests

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#7]
Contents of the tests directory are out-of-date. A set of unit tests needs to be written.

**Comment by luizfelippesr** [comment]
The tutorials listed in the docs provide a good set of tests. Perhaps, they should be integrated in the (full) test set through something like [nbval](https://github.com/computationalmodelling/nbval)

**Comment by 1313e** [comment]
Should the tests also be rewritten to `pytest`?

**Comment by luizfelippesr** [comment]
I don't think there is anyone against it. So, aye!

**Comment by luizfelippesr** [comment]
c337c435c8acc81f5d7fdd95cdd40ef7354993e9

**Comment by 1313e** [comment]
The remaining tests in [old_tests](https://github.com/IMAGINE-Consortium/imagine/tree/master/old_tests) must still be converted though.

**Comment by luizfelippesr** [comment]
## Testable templates 

With minor modifications, the (subclass) template files could become testable.  This would be useful in a number of ways, in particular: 
1) templates are meant to be the starting point for new IMAGINE users, so it is important that they are up-to-date and working;
2)  templates are supposed to exemplify most or all of the functionality available, so by testing them we will be testing most or all the features that can be used.

**Comment by luizfelippesr** [comment]
(I will give the above idea a try while testing the modifications introduced while working on #38)

**Comment by 1313e** [comment]
I did update the templates though to reflect the changes I made to all the base classes.

**Comment by luizfelippesr** [comment]
f02ade335af5f3ca9c5e05f50217c8ece124cafa

**Comment by luizfelippesr** [comment]
A test for `PipelineTemplate` is still missing.
