### ISSUE TITLE
Dealing with NaNs in measurements

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#82]
It would be useful, when dealing with image data, to have an option which automatically masks NaNs before computing the likelihood.

**Comment by 1313e** [comment]
NumPy allows you to create masked arrays.

**Comment by luizfelippesr** [comment]
Actually, this improvement may not be needed. Creating an IMAGINE `Masks` object for this case is as simple as:

```python
# Creates a Masks objects which will remove NaNs and Infs.
masks = img.observables.Masks()
for k in measurements:
    mask = np.isfinite(measurements[k].data)
    if np.all(mask):
        continue
    else:
        masks.append(name=k, data=mask)
```
I thought it would be complicated... but I simply forgot how the masking infrastructure worked.

This can be provided to a likelihood and get automatically applied to the simulations on the fly. E.g.
```python
# Creates likelihood which uses the masks
likelihood = img.likelihoods.SimpleLikelihood(measurements, mask_dict=masks)
```
It can even be provided to hammurabi...

I think I will just close this issue.

**Comment by luizfelippesr** [comment]
Actually, I will add that code snippet as an example in the Masks tutorial, since it may be useful for others.
