### ISSUE TITLE
Hammurabi Simulator must handle non-dummy fields

### ISSUE THREAD

**Issue by luizfelippesr** [IMAGINE-Consortium/imagine#9]
Currently, the Hammurabi Simulator (in the new_field branch) does not work with any non-dummy field (i.e. one can only use it with its builtin fields).  This needs to change.

 **Specification**
Because a python SWIG interface for hammurabiX is not yet ready, the Hammurabi simulator will dump the fields to disk and edit hammurabi's XML files so that it can use them. This should allow the user to include *any IMAGINE field* in a Hammurabi run by simply *adding it in the fields list*.

The temporary directory for this is provided in the initialization of the Hammurabi simulator (potentially, a different directory for the temporary XML files could also be set). If absent, it should default to  /run/shm (or /dev/shm ) or some other alternative. The temporary directory must be tested when the simulator is initialized. The temporary files must be removed when the simulator is deleted (i.e. during \_\_del\_\_ ).

**Comment by luizfelippesr** [comment]
@gioacchinowang, could you briefly describe how to set up HammurabiX to use external files for magnetic field, electron density and CR flux?

**Comment by gioacchinowang** [comment]
Briefly speaking, hamX reads in binary files, each value stored in the file for hamX v2.4 should always be in double data type. In v2.5 we have make this customizable, so the input values can be pre-defined, e.g., a 16-bit float. In terms of the order in the binary file:

1) scalar field in 3D coordinate x-y-z, with n_x positions in x dimension,
the order for storing the scalar field value is {i,j,k} for each x_i, y_j, z_k position, for example the first position is {0,0,1} and second is {0,0,2}. the last position is {n_x-1,n_y-1,n_z-1}

2) vector field in 3D, the spatial position ordering is the same as 1), but at each spatial position we have 3 values to store, the order for the field component is still x-y-z, for example magnetic field B = {B_x, B_y, B_z}, the first few elements in the binary file should be {B_x(0,0,0), B_y(0,0,0), B_z(0,0,0), B_x(0,0,1), B_y(0,0,1), B_z(0,0,1), ....,}, it's like when we read or write the file, we walk to the spatial position and read-in/ write-out the vector field component in a row, before walking to the next spatial position.

3) for the 4D CR case, the 4th dimension is the energy coordinate. We treat the CR flux file as a scalar field stored in 4D mesh, following the order of x-y-z-E.

**Comment by luizfelippesr** [comment]
Thanks! So, to read these in, all a have to do is to modify the XML parameter file in the following way?
```xml
  <!-- physical field in/out -->
  <fieldio>
    <breg read="1" write="0" filename="breg.bin"/> <!-- regular magnetic field (optional) -->
    <brnd read="1" write="0" filename="brnd.bin"/> <!-- random magnetic field (optional) -->
    <tereg read="1" write="0" filename="tereg.bin"/> <!-- thermal electron field (optional) -->
    <ternd read="1" write="0" filename="ternd.bin"/> <!-- random thermal electron field (optional) -->
    <cre read="1" write="0" filename="cre.bin"/> <!-- cosmic ray electron field (optional) -->
  </fieldio>
```
How is the random external field treated differently from the regular?

**Comment by luizfelippesr** [comment]
@gioacchinowang, while trying to read-in a thermal electron field from hammurabi, I keep getting the following error message:
```
hamx: /home/lfsr/hamx/source/grid/grid_tereg.cc:49: virtual void Grid_tereg::import_grid(const Param*): Assertion `!input.eof()' failed.
```

The full output is:
```
key: grid
key: observer
key: xattrib: value
key: yattrib: value
key: zattrib: value
key: observable
key: dmattrib: cue
key: dmattrib: filename
key: dmattrib: nside
key: faradayattrib: cue
key: faradayattrib: filename
key: faradayattrib: nside
key: observable
key: sync
attrib: cue
attrib: freq
attrib: filename
attrib: nside
attrib: cue
attrib: freq
attrib: filename
attrib: nside
key: grid
key: shell
key: oc_r_minattrib: value
key: oc_r_maxattrib: value
key: gc_r_minattrib: value
key: gc_r_maxattrib: value
key: gc_z_minattrib: value
key: gc_z_maxattrib: value
key: oc_r_resattrib: value
key: layerattrib: type
key: grid
key: shell
key: layer
key: auto
key: shell_numattrib: value
key: nside_simattrib: value
key: mask
attrib: cue
key: fieldio
key: bregattrib: read
key: bregattrib: write
key: bregattrib: filename
key: magneticfield
key: regularattrib: cue
key: regularattrib: type
key: magneticfield
key: regular
key: unif
key: bpattrib: value
key: bvattrib: value
key: l0attrib: value
key: fieldio
key: brndattrib: read
key: brndattrib: write
key: brndattrib: filename
key: magneticfield
key: randomattrib: cue
key: fieldio
key: teregattrib: read
key: teregattrib: write
key: teregattrib: filename
key: thermalelectron
key: regularattrib: cue
key: regularattrib: type
key: thermalelectron
key: regular
key: unif
key: n0attrib: value
key: r0attrib: value
key: grid
key: box_tereg
key: nxattrib: value
key: nyattrib: value
key: nzattrib: value
key: x_maxattrib: value
key: x_minattrib: value
key: y_maxattrib: value
key: y_minattrib: value
key: z_maxattrib: value
key: z_minattrib: value
key: fieldio
key: terndattrib: read
key: terndattrib: write
key: terndattrib: filename
key: thermalelectron
key: randomattrib: cue
key: fieldio
key: creattrib: read
key: creattrib: write
key: creattrib: filename
key: cre
attrib: cue
key: cre
key: unif
key: alphaattrib: value
key: r0attrib: value
key: E0attrib: value
key: j0attrib: value
hamx: /home/lfsr/hamx/source/grid/grid_tereg.cc:49: virtual void Grid_tereg::import_grid(const Param*): Assertion `!input.eof()' failed.
Aborted (core dumped)
```

**Comment by luizfelippesr** [comment]
The previous problem was caused by the use of `numpy.save`.  However, using  `numpy.ndarray.tofile` seems to work. 

I still have some questions. If I instruct hammurabi to read in a field from file, will it still compute the associated quantity and sum it? 

In other words, if I provide a regular TE field, using `<tereg read="0" write="0" filename="tereg.bin"/>`, and also have `<thermalelectron><regular cue="1" type="unif">` ,  will hammurabi ignore the setting in `<unif>` or will it sum the two?

**Comment by luizfelippesr** [comment]
6ae0353264ddfe8c13dc6e5c16fb77688f6ee6a9

**Comment by luizfelippesr** [comment]
With this commit 96de1760b4f2b940eeb09d29662128b5bc24fb46 we are almost there. 

 I will do a little bit of tweaking to make the Hammurabi simulator a little bit more user friendly before closing the issue.
